#!/bin/bash
##   ____  _
##  / __ \| |
## | |  | | |_   _ _ __ ___  _ __   __ _
## | |  | | | | | | '_ ` _ \| '_ \ / _` |
## | |__| | | |_| | | | | | | |_) | (_| |
##  \____/|_|\__, |_| |_| |_| .__/ \__,_|
##			__/ |		 | |
##		   |___/		  |_|
##
## Script to handler Minecraft servers
## Author > Tristiisch

# PARAMETRE

# Commandes
START="start"
STOP="stop"
SEE="see"
BACKUP="backup"
RESTART="restart"
SSH="ssh"



# Format de la date 
DATE="$(date +"%a %d %b %Y %H:%M")"
DATE_DAY="$(date +"%j")"

# Dossier des serveurs (dossier qui contient les dossiers qui contiennent les fichiers du serveur). Il est recommand?e cr?un dossier dans /home tel que /home/<nom de votre network> pour y mettre tous les autres serveurs.
SERVEUR_DIR="/home/serveurs"

# Commande en cas d'erreur ou d'arguments non d?nie
USAGE="\e[0;36mUsage >\n$(basename "$0") $START|$STOP|$RESTART ALL|<server>\n$(basename "$0") $SEE <server> -t\n$(basename "$0") deploy|deployto|autodeploy dev|master ALL|<server>\n$(basename "$0") unban <ip>\e[0;36m\n$(basename "$0") $BACKUP\n$(basename "$0") backupbdd|backupserv\nTous les serveurs : $(ls $SERVEUR_DIR)\e[0m"

# Nom des script qui lance le serveur (qui lance le .jar). Par default start.sh
STARTSH="start.sh"

REPO_DIR="/home/repo"

VERSION="1.16.5"
VERSION_WATERFALL="1.17"

PAPER_API_VERSION="https://purpur.pl3x.net/api/v1/purpur/$VERSION/latest"
PAPER_API_DOWNLOAD="$PAPER_API_VERSION/download"
WATERFALL_API_VERSION="https://papermc.io/api/v1/waterfall/$VERSION_WATERFALL/latest"
WATERFALL_API_DOWNLOAD="$WATERFALL_API_VERSION/download"

spigot_file="paperclip.jar"
bungee_file="Waterfall.jar"

# Nom de l'utilisateur avec lequel les serveurs se lance. Par default root
USER_EXE="minecraft"

# Serveurs:
# ALL="$(ls $SERVEUR_DIR)"
ALL="bungee1 zta1 creatif1 pvpkit1 lobby1 lobby2 auth1 buildeur"

# Backup mysql
BDD_USER="backup"
BDD_PASSWORD="K53SHychsL4_iRij3jY8TiTT87acdiVlyANCsXtya88vl8eJGw"
BDD_HOST="localhost"

BACKUP_DIR="/home/.backup"

# FTP sauvegarde ################################
# IP (chiffr?u dns) du ftp
FTP_HOST=""
# Port du ftp (default 21)
FTP_PORT="21"
# Nom d'utiliser du compte ftp
FTP_USER=""
# Mdp du compte ftp
FTP_PASSWORD=""
# Dossier des backups sur le ftp
FTP_DIR="/serveurs/"

DEPLOYTO_SECOND_BEFORE_SHUTDOWN="10"

#- - - - - - - - - - - - - - - - - - - - - - - - - - UNBAN IP - - - - - - - - - - - - - - - - - - - - - - - - - -
if [ "$1" = "unban" ]; then
	if [ -n "$2" ]; then
		route del "$2" reject
		fail2ban-client set sshd unbanip $2
		fail2ban-client set mysqld-auth unbanip $2
		sed -i '/$2/d' /etc/hosts.deny
	else
		echo -e "\e[35mUsage\e[0;35m $0 unban <ip>\e[0m"
	fi
	exit $?
elif [ "$1" = "backupbdd" ]; then
	echo -e "\e[32mCréation de la backup bdd ...\e[0m"
	SIZE_BYTES=$(mysql --skip-column-names -h $BDD_HOST -u $BDD_USER -p$BDD_PASSWORD <<< 'SELECT SUM(data_length) AS "size_bytes" FROM information_schema.TABLES;')
	mysqldump -h $BDD_HOST -u $BDD_USER -p$BDD_PASSWORD -A -x | pv --progress --size $SIZE_BYTES > "$BACKUP_DIR/$DATE_DAY | databases.sql"
#- - - - - - - - - - - - - - - - - - - - - - - - - - - REDIS - - - - - - - - - - - - - - - - - - - - - - - - - -
elif [ "$1" = "redis" ]; then
	redis-cli -a 1rWS1Fmj7s4snEDCQgw3Mcznf8ShfrLZpPkKtstu5coV9PpDI1
#- - - - - - - - - - - - - - - - - - - - - - - - - - USAGE - - - - - - - - - - - - - - - - - - - - - - - - - -
else
	echo -e "\e[31m'${*:0}' Unknow\n$USAGE\e[0m"
fi
